name: cal-itp/customer-success

services:
  docs:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: cal-itp/customer-success:docs
    entrypoint: []
    command: sleep infinity
    ports:
      - "8000"
    volumes:
      - ./:/customer-success
