name: customer-success

services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: cal-itp/customer-success:dev
    entrypoint: []
    command: sleep infinity
    ports:
      - "8000"
    volumes:
      - ./:/home/calitp/customer-success
