name: "Deals Pipeline Request Form"
description: Request a deals pipeline to Hubspot
title: "[Deals Pipeline Request]: "
labels:
  - "deals-pipeline"
body:
  - type: markdown
    attributes:
      value: |
       ### If you need a pipeline...
  - type: input
    id: pipeline
    attributes:
      label: Deals Pipeline Request
      description: Name of the Deals Pipeline
      placeholder: Ex. Data Assessment Outreach, Payments Outreach, etc.
    validations:
      required: true
  - type: input
    id: access
    attributes:
      label: Who needs access?
      description: Please add all first and last names.
      placeholder: "Ex: John Smith, Maria Johnson"
    validations:
      required: true
  - type: textarea
    id: Problem
    attributes:
      label: What problem are you trying to solve for?
      description: Input as much detail as possible.
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: What is the goal of the pipeline you are trying to solve for?
      description: Input as much detail as possible.
    validations:
      required: true
  - type: input
    id: stages
    attributes:
      label: What stages would you like in the pipeline?
      description: Stages in Hubspot are considered as statuses
      placeholder: Ex. To-Do, In Progress, Review, Done, etc.
  - type: input
    id: maintenance
    attributes:
      label: Who will be responsible for maintaining this pipeline in Hubspot?
      description: Describe the person(s) or team responsible for maintaining this property.
      placeholder: Ex. Customer Success, Data Quality team, or Anthony and Jane.
  - type: dropdown
    id: usage
    attributes:
      label: Have you used an exisiting pipeline in Hubspot?
      description: Payments pipeline, Data Assessment Outreach, etc.
      options:
        - "Yes"
        - "No"
        - "Unsure"
