name: Property Request Form
description: File a property request for Hubspot
title: "[Property Request]: "
labels:
  - "property"
body:
  - type: markdown
    attributes:
      value: |
       ### Properties in Hubspot are considered fields in most other platforms. They are attached to each Hubspot Object (Company, Contact, Tickets, etc.) and can be completely customized. Add what custom property you need in Hubspot.
  - type: input
    id: custom-property-name
    attributes:
      label: Name of Custom Property
      description: What should we call this new property?
      placeholder: ex Company Type
  - type: textarea
    id: what-problem
    attributes:
      label: What is the problem that this is solving?
      description: Use this space to describe the problem you are solving with this custom property
    validations:
      required: true
  - type: dropdown
    id: object-association
    attributes:
      label: Object Association
      description: What object do you want this new property associated withe in Hubspot
      options:
        - Contacts
        - Companies
        - Deals
        - Tickets
        - Other
  - type: input
    id: implementation-date
    attributes:
      label: When does this property need to be implemented?
      description: Add a date for implementation
      placeholder: 8/1/22
  - type: dropdown
    id: questions
    attributes:
      label: Not sure what you need?
      description: The CRM team can schedule time to determine the best property for your needs? Let us know!
      options:
        - "Yes"
        - "No"
        - "Unsure"
