name: Property Request Form
description: File a property request for Hubspot
title: "[Property Request]: "
labels:
  - "property"
body:
  - type: markdown
    attributes:
      value: |
       ### Properties in Hubspot are considered fields in most other platforms. They are attached to each Hubspot Object (Company, Contact, Tickets, etc.) and can be completely customized. Add what custom property you need in Hubspot.
  - type: input
    id: custom-property-name
    attributes:
      label: Name of Custom Property
      description: What should we call this new property?
      placeholder: ex Company Type
  - type: textarea
    id: what-problem
    attributes:
      label: What is the problem that this is solving?
      description: Use this space to describe the problem you are solving with this custom property
    validations:
      required: true
  - type: dropdown
    id: object-association
    attributes:
      label: Object Association
      description: What object do you want this new property associated with in Hubspot
      options:
        - Contacts
        - Companies
        - Deals
        - Tickets
        - Other
  - type: checkboxes
    id: company-type
    attributes:
      label: If the Object Association is Company: Which company type does this information apply to?
      description: Most custom properties only apply to one type of company, such as a transit agency or a vendor. Please select which company type this property is applicable for. You may select more than one option. **If your property is not associated with a company, please select N/A.**
      options:
        - label: Transit Agency
        - label: Vendor
        - label: N/A
        - label: Unsure
  - type: checkboxes
    id: pipeline-type
    attributes:
      label: If the Object Association is Deal: Which pipeline does this information apply to?
      description: Most custom properties only apply to one specific pipeline, such as the Payments Pipeline or the Software for Scheduling Pipeline. Please select which pipeline this property is applicable for. You may select more than one option. **If your property is not associated with Deals, please select N/A.**
      options:
        - label: Payments Pipeline
        - label: Contract Outreach
        - label: MDIP Outreach
        - label: GRaaS
        - label: Cubic/Umo API Key Outreach
        - label: Cal-ITP Benefits
        - label: Software for Scheduling
        - label: Payments Dashboard
        - label: Relevant Pipeline has not been created yet
        - label: N/A
        - label: Unsure
  - type: input
    id: maintaining
    attributes:
      label: Who is responsible for updating and maintaining this property?
      description: Describe the person(s) responsible for maintaining this property. Add any additional details on existing data that should be imported into the CRM.
      placeholder: John and Jim with Cal-ITP will maintain this property. We have existing data we would like imported in.
  - type: dropdown
    id: updating-cadence
    attributes:
      label: Updating Cadence
      description: How often will this property be updated?
      options:
        - Daily
        - Weekly
        - Monthly
        - Quarterly
        - Yearly
        - Other
  - type: input
    id: implementation-date
    attributes:
      label: When does this property need to be implemented?
      description: Add a date for implementation
      placeholder: 8/1/22
  - type: dropdown
    id: questions
    attributes:
      label: Not sure what you need?
      description: The CRM team can schedule time to determine the best property for your needs? Let us know!
      options:
        - "Yes"
        - "No"
        - "Unsure"
