name: MkDocs Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"

jobs:
  mkdocs-publish:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # 7.0.0

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@d77dd03172e96abbcdb081d8c948224762033653
        env:
          REQUIREMENTS: docs/requirements.txt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
