name: Netlify MkDocs Preview

on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"

jobs:
  mkdocs-deploy-preview:
    name: Deploy Netlify Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "docs/requirements.txt"

      - name: Build MkDocs website
        run: |
          pip install -r docs/requirements.txt
          mkdocs build

      - name: Install Netlify CLI
        run: npm install --location=global netlify-cli@17.x.x

      # Don't expose secrets to any other process other than the `netlify` cli;
      # don't risk rogue dependencies pulling our secrets
      - name: Deploy Preview to Netlify
        run: |
          netlify deploy \
            --alias="${GITHUB_REPOSITORY#*/}-${{ github.event.number }}" \
            --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --dir="site" \
            --site=${{ secrets.NETLIFY_PREVIEW_APP_SITE_ID }}

      - name: Add Netlify link PR comment
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const hostnameSuffix = "cal-itp-previews.netlify.app"
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview url: https://${context.repo.repo}-${{ github.event.number }}--${hostnameSuffix}`,
            })
