name: Create Monthly Report Issue

on:
  workflow_dispatch:
  schedule:
    # 16:16 UTC on the 2nd of every month
    - cron: 16 16 2 * *

jobs:
  create-monthly-report-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      # Get last month's name as a variable
      # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#setting-an-output-parameter
      - id: set_output
        run: |
          echo "month=$(date -d 'last month' +%B)" >> $GITHUB_OUTPUT

      - id: create_issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # The `--body-file -` option below uses the multiline content from stdin for the body.
        # See: https://github.com/cli/cli/issues/595
        run: |
          echo -e "[${{ steps.set_output.outputs.month }} Report](https://docs.google.com/spreadsheets/d/1FDNOekxKzIrtuxmSrGEwcY9UQFv6OivDEJVph3dQwII/edit?gid=0#gid=0)\n\n## To-Do\n\n- [ ] Draft, edit, and send the ${{ steps.set_output.outputs.month }} monthly report" | \
          gh issue create \
            --title "Customer Success ${{ steps.set_output.outputs.month }} Monthly Report Highlights" \
            --body-file - \
            --label "reporting" \
            --assignee o-ram \
            --repo $GITHUB_REPOSITORY
