name: Notify Slack for New User requests

on:
  issues:
    types: [labeled]

jobs:
  new-user-notify-slack:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'new-user')
    steps:
      - name: Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: cal-itp-bot
          SLACK_MSG_AUTHOR: cal-itp-bot
          SLACK_ICON: https://github.com/cal-itp-bot.png?size=48
          SLACK_MESSAGE: "A Hubspot new user request was submitted: ${{ github.event.issue.html_url }}"
          MSG_MINIMAL: true
